### ISSUE TITLE
Why express dependencies are needed?

### ISSUE THREAD

**Issue by anaibol** [tracworx/nestjs-dataloader#122]
When using apollo server with fastify, apollo-server-express and @nestjs/platform-express are not needed. And this (great) nestjs module just works!

**Comment by eoin-obrien** [comment]
Thanks for opening this issue! Good catch, I'll drop the peer dependency on `apollo-server-express` and keep `apollo-server-express` and `@nestjs/platform-express` as dev dependencies for our end-to-end tests.
