### ISSUE TITLE
Bump up peerDependencies versions

### ISSUE THREAD

**Issue by adam-tkaczyk-mck** [tracworx/nestjs-dataloader#246]
**Describe the bug**
Could you bump up the `@nestjs/common`, `@nestjs/core`, `@nestjs/graphql` and `graphql` version in `peerDependencies`? I'm using nest v9, it's working fine with v9, the only error is during installation

**To Reproduce**
1. Use newest version of NestJS
2. run `npm i`

**Expected behavior**
I'm able to install w/o `--legacy-peer-deps` flag

**Screenshots**
<img width="1060" alt="CleanShot 2023-02-22 at 17 36 53@2x" src="https://user-images.githubusercontent.com/108651952/220695545-d1a20197-4570-4847-976f-d3792ea352b0.png">

**Comment by eoin-obrien** [comment]
Thanks for flagging this! The updated peer dependency should be live in v1.2.0 now.

**Comment by adam-tkaczyk-mck** [comment]
@eoin-obrien Thx for quick fix!

Could you update `"graphql": "^15.0.0"` to support `^16.0.0` also?

**Comment by eoin-obrien** [comment]
> Could you update `"graphql": "^15.0.0"` to support `^16.0.0` also?

Sure thing! This should be live as `v1.2.1` now.
